Repository sandialabs/compadre, pull requests merged in 2020-05, with the labels that each got.

#185 Divergence free gradient able to be evaluated everywhere (not just target site)
  examples/CMakeLists.tribits.cmake
  examples/CMakeLists.txt
  examples/GMLS_DivergenceFree.cpp
  examples/GMLS_Tutorial.hpp
  src/CMakeLists.tribits.cmake
  src/CMakeLists.txt
  src/Compadre_GMLS.cpp
  src/Compadre_GMLS.hpp
  src/Compadre_GMLS_Basis.hpp
  src/Compadre_GMLS_Targets.hpp
  src/Compadre_LinearAlgebra.cpp
  src/Compadre_USER_ManifoldTargetFunctionals.hpp
  src/Compadre_USER_StandardTargetFunctionals.hpp
  src/basis/Compadre_DivergenceFreePolynomial.hpp
  src/basis/Compadre_ScalarTaylorPolynomial.hpp
  src/basis/DivergenceFree3D.hpp
  src/constraints/Compadre_CreateConstraints.hpp
Labels: READY FOR TESTING, TOOLKIT

#192 Fix Snapshot Unit Test
  scripts/snapshot_into_trilinos.py
Labels: bug

#195 Added keep_coefficients argument to generateAlphas()
  examples/GMLS_Device.cpp
  examples/GMLS_SmallBatchReuse_Device.cpp
  examples/GMLS_Vector.cpp
  src/Compadre_GMLS.cpp
  src/Compadre_GMLS.hpp
Labels: TOOLKIT, enhancement

#196 Fixed bug that affected certain number of batches > 1
  examples/GMLS_Device.cpp
  src/Compadre_GMLS.cpp
Labels: TOOLKIT

#199 Fixed populating CMAKE_INSTALL_LIBDIR and including header for subdirectories.
  CMakeLists.txt
  src/CMakeLists.tribits.cmake
  src/CMakeLists.txt
  src/Compadre_GMLS.cpp
  src/Compadre_GMLS.hpp
  src/Compadre_PointCloudSearch.hpp
Labels: TOOLKIT, bug, fixed

#200 Update to Python call for keeping coefficients, number of batches, and weighting type
  examples/Python_3D_Convergence.py.in
  python/GMLS_Module.py.in
  python/GMLS_Module_wrap.cxx
  python/GMLS_Python.hpp
  python/run_swig.sh
Labels: TOOLKIT
