Repository sandialabs/compadre, pull requests merged in 2020-04, with the labels that each got.

#177 Refactored AnalyticFunction and most derived classes
  examples/CMakeLists.txt
  examples/Canga_Test_Intercomparison.cpp
  examples/Compadre_ReactionDiffusion.cpp
  physics/Compadre_ReactionDiffusion_BoundaryConditions.cpp
  physics/Compadre_ReactionDiffusion_BoundaryConditions.hpp
  physics/Compadre_ReactionDiffusion_Operator.cpp
  physics/Compadre_ReactionDiffusion_Operator.hpp
  physics/Compadre_ReactionDiffusion_Sources.cpp
  src/Compadre_AnalyticFunctions.cpp
  src/Compadre_AnalyticFunctions.hpp
  test_data/parameter_lists/reactiondiffusion/parameters_template.xml
  test_data/utilities/variational_convergence.py
Labels: HARNESS

#179 Added residual() function that can be called after solve() on ProblemT
  src/Compadre_ProblemT.cpp
  src/Compadre_ProblemT.hpp
  src/Compadre_SolverT.cpp
  src/Compadre_SolverT.hpp
Labels: HARNESS

#182 Added GradientOfVectorPointEvaluation for several bases
  examples/GMLS_Tutorial.hpp
  examples/GMLS_Vector.cpp
  src/Compadre_GMLS_Targets.hpp
Labels: TOOLKIT

#176 Resolve "Create Script to Snapshot Compadre into Trilinos"
  scripts/snapshot_into_trilinos.py
Labels: TOOLKIT, feature request

#173 Resolve "Create TriBITS Build Alongside Raw CMake Build"
  CMakeLists.txt
  cmake/Dependencies.cmake
  cmake/bob.cmake
  examples/CMakeLists.tribits.cmake
  examples/CMakeLists.txt
  examples/GMLS_Manifold.py.in
  examples/GMLS_Manifold_Multiple_Evaluation_Sites.py.in
  examples/GMLS_Staggered_Manifold.py.in
  scripts/snapshot_into_trilinos.py
  scripts/trilinos-configure.sh
  src/CMakeLists.tribits.cmake
  src/CMakeLists.txt
Labels: TOOLKIT
